version: 2


jobs:
  test:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Run Test File
          command: |
             ./.test/test 
             
    # publish-github-release:
    #   steps:
    #     - run: 
    #         name: "Publish Release on GitHub"
    #         command: | 
    #           go get -u github.com/tcnksm/ghr
    #           ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - test
          # filters:
          #   tags:
          #     only: 
          #       - /^\d+\.\d+\.\d+$/
      - hold:
          requires: test
          type: approval 
# On approval of the `hold` job, any successive job that requires the `hold` job will run. 
# In this case, a user is manually triggering the deploy job.
      # - publish-github-release:
      #     requires:
      #       - hold
      #     filters:
      #       branches:
      #         ignore: 
      #           - /.*/
      #       tags: 
      #         only: 
      #           - /^\d+\.\d+\.\d+$/

